# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiallistquestion',
            name='projeto',
            field=models.CharField(max_length=50, verbose_name=b'Projeto'),
        ),
        migrations.AlterField(
            model_name='question',
            name='projeto',
            field=models.CharField(max_length=50, verbose_name=b'Projeto'),
        ),
    ]
